### ISSUE TITLE
Create data tip that is a different color for "thought questions" on intro materials.

### ISSUE THREAD

**Issue by lwasser** [NEON-WorkWithData/neon-data-institute-2016#1]

**Comment by lwasser** [comment]
https://docs.google.com/document/d/1gN4BA_AqfQLD7JPLw6sZxS6M7vy680xiEEyVXrV90Bk/edit

**Comment by mjones01** [comment]
I have create a notice2 that is light green for this.  We can change color/name as desired.  (PR with the change not yet created/merged).

**Comment by lwasser** [comment]
ok - please don't merge any structural changes to the site template elements, submit all as PRs. Thank you!

**Comment by mjones01** [comment]
This new style is showing up visually different from the Data Tips with
1. no edge around the text (e.g. the edge of green is essentially the edge of the text and looks cramped) and 
2. square corners instead of rounded.  
Can the styling being matched to the Data Tip styling -- or at least increase the amount of color around the edge?

**Comment by lwasser** [comment]
@mjones01 can we mark this complete?

**Comment by mjones01** [comment]
yep.
