### ISSUE TITLE
Wednesday - data download link broken 

### ISSUE THREAD

**Issue by mjones01** [NEON-WorkWithData/neon-data-institute-2016#58]
http://neon-workwithdata.github.io/neon-data-institute-2016/compare-lidar-to-field-data-R/ 

Currently this data download button just redirects to the same page.  The appropriate data also don't appear to be on FigShare.

**Comment by lwasser** [comment]
Megan - the data subsets aren't done yet.

Also wed and Thursday materials aren't done so that is why there are empty links on those pages. You can leave this issue open but because I'm actively working on these things, I wouldn't worry about editing these pages beyond adding learning objectives at this point because I know it's all not done and am working on it all at the same time.

**Comment by mjones01** [comment]
I'm going to close this issues as Wednesday and Thursday lessons are still to be reviewed, and the correct include files will be added at that time.

**Comment by lwasser** [comment]
Perfect.
